### ISSUE TITLE
No longer working (Feb 2024)

### ISSUE THREAD

**Issue by XanoPhobious** [jeroentvb/spicetify-volume-percentage#2]
Since the beginning of February 2024, this no longer working.
Please update.

**Comment by jeroentvb** [comment]
I've just checked the extension, and it seems to be working fine on my end. I'm using the latest Spotify and Spicetify. What versions are you using?

**Comment by XanoPhobious** [comment]
The one I'm currently using is:
Spotify for Windows
1.2.30.1135.g02fef27a
Spicetify v2.31.2

This is what it looks like to me.
![vol1](https://github.com/jeroentvb/spicetify-volume-percentage/assets/97661288/2dda28d5-6d3e-40e2-a790-f2d490e0488a)
![vol2](https://github.com/jeroentvb/spicetify-volume-percentage/assets/97661288/d4bd3115-8e8f-4290-81d0-830c7449e038)

Note: I install manually; not thru Marketplace.

**Comment by jeroentvb** [comment]
I just tested on windows as well, and it is working just fine. I am using spotify 1.2.31 though.
![afbeelding](https://github.com/jeroentvb/spicetify-volume-percentage/assets/36192730/1523dacd-9691-449c-a256-c56d9ed71a23)

Can you please update spotify/spicetify and make sure you don't have any active theme or other extensions that modify the volume bar in any way?

**Comment by XanoPhobious** [comment]
Apparently all I have to do is re-install Spotify.
I'm sorry for troubling you.
